### ISSUE TITLE
GitHub URL wraps over two lines in Firefox

### ISSUE THREAD

**Issue by ewels** [ewels/opensource.scilifelab-theme#3]
The final GitHub URL wraps over two lines on the [project page](http://opensource.scilifelab.se/projects/cutadapt/) in Firefox:
![image](https://cloud.githubusercontent.com/assets/465550/6634907/994044aa-c95f-11e4-991c-711c2f61703c.png)

It looks fine in Chrome:
![image](https://cloud.githubusercontent.com/assets/465550/6634910/a107534a-c95f-11e4-95d2-0d1e8da43369.png)

Need to either add a line break to the template or do some CSS magic to stop the URL from breaking onto a new line.

**Comment by robinandeer** [comment]
CSS magic will do the trick :wink:

``` css
a { white-space: nobreak; }
```
